mode = "Dominant"            # "Blend" or "Dominant"
speed = 140.0
vision_radius = 160.0
threat_radius = 120.0
sep_radius = 170.0
arena = [600.0, 900.0]
entity_radius = 10.0
initial_count = 60         # will be coerced to a multiple of 3 and min 9
cell_size = 100.0          # ~max(vision_radius, sep_radius)

[weights]
chase = 1.0
flee = 1.2
separation = 0.35

